name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.5.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run pre-commit hooks
        run: SKIP=black,isort,flake8 poetry run pre-commit run --all-files

      - name: Run black
        run: poetry run black --check --diff .

      - name: Run isort
        run: poetry run isort --check --diff .

      - name: Run flake8
        run: poetry run flake8 .
